'use strict';

var four51 = {};
four51.app = angular.module('451order', [
    'ngResource',
    'ngRoute',
    'ngAnimate',
    'ngSanitize',
    'ngCookies',
    'ngTouch',
    'ui.validate',
    'ui.mask',
    'headroom',
    'ui.bootstrap',
    'angulartics',
    'angulartics.google.analytics',
    'ngAutocomplete',
    'OrderCloud-AnonRouter',
    'OrderCloud-SpecForms',
    'OrderCloud-CategoryCollapse',
    'OrderCloud-HamburgerNavigation',
    'OrderCloud-HeaderNavigation',
    'OrderCloud-LargeAddressListSearch',
    'OrderCloud-ProductLightbox',
    'OrderCloud-ProductSearchInput',
    'OrderCloud-Breadcrumbs',
    'OrderCloud-SameAsShippingCheckbox',
    'OrderCloud-Minicart',
    'OrderCloud-ContentModal3',
    'OrderCloud-ContentModal4',
    'OrderCloud-ContentModal5',
    'OrderCloud-ContentModal7',
    'OrderCloud-CategoryModal',
]);
